# Generated by Django 6.0.6 on 2026-06-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'runs_tag',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='runs', to='runs.tag'),
        ),
    ]
