# Generated by Django 6.0.6 on 2026-06-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0006_seed_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='progress_message',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
